version: '3.0'
services:
  db:
    image: postgres:14.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: spshimmsa23
      POSTGRES_DB: hackatondb
      POSTGRES_USER: analytic23
      PGDATA: /pgdata
    volumes:
      - ./db:/var/lib/postgresql/data:rw
      - ./sql_script.txt:/docker-entrypoint-initdb.d/init.sql

  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"